from simple_genetic_algorithm import SGA

ALNUM = ["0", "1"]
VAR_STRING_LEN = 20
NUMBER_OF_VARIABLES = 4
VARIABLE_LEN = VAR_STRING_LEN / NUMBER_OF_VARIABLES
PROBABILITY_OF_MUTATION = 0.05
PROBABILITY_OF_CROSSOVER = .5
NUM_STRINGS = 40
NUM_GENERATIONS = 1000
DOMAIN_MIN = -5.12
DOMAIN_MAX = 5.12

#TODO docstring
def dejong(*xs):
    return sum(xi ** 2 for xi in xs)

print("Running Simple Genetic Algorithm on De Jong Sphere benchmark function")
SGA(dejong, NUM_STRINGS, ALNUM, VAR_STRING_LEN, VARIABLE_LEN, DOMAIN_MIN, DOMAIN_MAX, NUM_GENERATIONS,
    PROBABILITY_OF_MUTATION, PROBABILITY_OF_MUTATION)
