# from TP.simple_genetic_algorithm import SGA

from simple_genetic_algorithm import SGA

BIN_ALPHABET = ["0", "1"]
STRING_LEN = 20
NUMBER_OF_VARIABLES = 4
VARIABLE_LEN = 5
PROBABILITY_OF_MUTATION = 0.05
# PROBABILITY_OF_CROSSOVER = 0.5
NUM_STRINGS = 40
NUM_GENERATIONS = 1000
DOMAIN_START = -5.12
DOMAIN_END = 5.12


def dejong(*xs):
    return sum(xi ** 2 for xi in xs)


SGA(dejong, NUM_STRINGS, BIN_ALPHABET, STRING_LEN, VARIABLE_LEN, DOMAIN_START, DOMAIN_END, NUM_GENERATIONS,
    PROBABILITY_OF_MUTATION)
